version: "3"
services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
#doesn't work yet
    # extra_hosts:
    #   - "mtrautne.42.fr:127.0.0.1"
    # restart: always
    networks:
      inception:
networks:
  inception:
    ipam:
      driver: default
      config:
        - subnet: 192.168.122.0/24