version: "3"
services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
#doesn't work yet
    extra_hosts:
      - "mtrautne.42.fr:192.168.122.2"
    restart: always
    networks:
      inception:
        ipv4_address: 192.168.122.2
networks:
  inception:
    ipam:
      driver: default
      config:
        - subnet: 192.168.122.0/24