services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    secrets:
      - credentials
    ports:
      - "443:443"
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    secrets:
      - credentials
      - db_password
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    secrets:
      - credentials
      - db_root_password
      - db_password
    restart: always

volumes:
  wordpress_vol:
    name: wordpress_vol
    driver: local
    driver_opts:
      type: none
      device: /home/mtrautne/data/wordpress
      o: bind

  mariadb_vol:
    name: mariadb_vol
    driver: local
    driver_opts:
      type: none
      device: /home/mtrautne/data/mariadb
      o: bind

networks:
 inception:
    driver: bridge
    name: inception_network

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  credentials:
    file: ./secrets/credentials.txt