version: '3'

services:
  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ./requirements/nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "443:443"
  #     env_file:
  #     - .env
  #   restart: always
  #   networks:
  #     inception:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always

networks:
  inception: