services:
  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ./requirements/nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "443:443"
  #   env_file:
  #   - .env
  #   volumes:
  #     - wordpress:/var/www/html
  #   networks:
  #     - inception
  #   restart: always

  # wordpress:
  #   container_name: wordpress
  #   build:
  #     context: ./requirements/wordpress
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   environment:
  #     - WORDPRESS_DB_HOST=mariadb:3306
  #     - WORDPRESS_DB_USER=wordpress
  #     - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
  #     - WORDPRESS_DB_NAME=wordpress
  #   volumes:
  #     - wordpress:/var/www/html
  #   networks:
  #     - inception
  #   restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    secrets:
      - db_root_password
      - db_password
      - credentials

    volumes:
      - mariadb_vol:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception
    restart: always

volumes:
#   wordpress_vol:
#     name: wordpress
#     driver: local
#     driver_opts:
#       type: none
  #todo: change path to the correct path
#       device: ./home/mtrautne/data/wordpress
#       o: bind

  mariadb_vol:
    name: mariadb_vol
    driver: local
    driver_opts:
      type: none
      #todo: change path to the correct path
      device: /Users/mtrautne/Documents/inception/home/mtrautne/data/mariadb
      o: bind

networks:
 inception:
    driver: bridge
    name: inception

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  mysql_password:
    file: ./secrets/db_password.txt
  credentials:
    file: ./secrets/credentials.txt